modLoader="javafml"
loaderVersion="[${forge},)"
license="WTFPL"
issueTrackerURL="https://github.com/SrRapero720/EmbeddiumPlus/issues"
displayTest="IGNORE_SERVER_VERSION"

[[mods]]
    modId="embeddiumplus"
    version="${version}"
    displayName="Embeddium++"
    displayTest="IGNORE_SERVER_VERSION"
    logoFile="icon.png"
    authors="SrRapero720"
    credits="TeamDeusVult is the original author"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/embeddium-plus"
    description='''
    Adds Extra Settings to Embeddium.
    '''

[[dependencies.embeddiumplus]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.embeddiumplus]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.embeddiumplus]]
    modId="embeddium"
    mandatory=true
    versionRange="[${embeddium},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.embeddiumplus]]
    modId="textrues_embeddium_options"
    mandatory=true
    versionRange="*"
    ordering="AFTER"
    side="CLIENT"