modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="${modlicense}"
issueTrackerURL="https://github.com/${github_project}/issues"
[[mods]]
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    logoFile="icon.png" #optional
    authors="${modauthor}" #optional
    credits="${modcredits}"
    displayURL="https://legacy.curseforge.com/minecraft/mc-mods/embeddium-plus"
    description='''${mod_description}'''
[[dependencies.${modid}]]
    modId="forge"
    mandatory=true
    versionRange="${fgrange}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcrange}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${modid}]]
    modId="embeddium"
    mandatory=true
    versionRange="${embeddiumrange}"
    ordering="AFTER"
    side="CLIENT"