modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="WTFPL"
[[mods]]
modId="embeddium_extras"
version="${file.jarVersion}"
displayName="Embeddium Extras"
logoFile="templatemod.png" #optional
authors="SrRapero720" #optional
credits="TeamDeusVult is the original author"
description='''
Adds Extra Settings to Embeddium.
'''
[[dependencies.rubidium_extras]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubidium_extras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubidium_extras]]
    modId="embeddium"
    mandatory=true
    versionRange="[0.2.6,)"
    ordering="AFTER"
    side="BOTH"